version: 2
updates:
- package-ecosystem: 'github-actions'
  directory: /
  schedule:
    interval: 'weekly'
    day: 'monday'
    time: '06:00'
    timezone: 'America/New_York'
- package-ecosystem: 'npm'
  directory: /
  schedule:
    interval: 'weekly'
    time: '06:00'
    timezone: 'America/New_York'
