name: "Contentful Migration Automation"
description: "Fully automated and configurable migrations against a contentful space"
inputs:
  delete_feature:
    description: "The head branch will be deleted after it was merged"
  set_alias:
    description: "The master will be aliased to the new master"
  master_pattern:
    description: "The pattern that should be used for the new master"
  feature_pattern:
    description: "The pattern that should be used for the new feature"
  version_content_type:
    description: "The content-type that tracks the version"
  version_field:
    description: "The field that carries the version number"
  migrations_dir:
    description: "The directory to look for migrations"
  space_id:
    description: "The id of the contentful space"
  management_api_key:
    description: "The management-api key for contentful"

outputs:
  environment_url:
    description: "Contentful environment URL"
  environment_name:
    description: "Contentful environment name"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "red"
