name: 'Contentful Action'
description: 'Run a Migration against your Contentful space'
inputs:
  actions:
    description: "The actions to run on this workflow. Comma separated string. Example: `createEnvironment, createCDAToken, applyMigration, updateAlias, cleanUpEnvironments`"
  delete_feature:
    description: "The head branch will be deleted after it was merged"
  set_alias:
    description: "The master will be aliased to the new master"
  contentful_alias:
    description: "Specify a different alias to update (default: master)"
  master_pattern:
    description: "The pattern that should be used for the new master"
  feature_pattern:
    description: "The pattern that should be used for the new feature"
  version_content_type:
    description: "The content-type that tracks the version"
  version_field:
    description: "The field that carries the version number"
  migrations_dir:
    description: "The directory to look for migrations"
  space_id:
    description: "The id of the contentful space"
  management_api_key:
    description: "The management-api key for contentful"
  delay:
    description: "The default delay between attempts for repeatable actions"
  max_number_of_tries:
    description: "The number of times action will retry a repeatable action"
  create_cda_token:
    description: "CDA token will be created for ephemeral environment"
    required: false
    default: true
  default_branch_name: 
    description: "Override the repository default branch name. Ex: `production` to track a separate release branch"
  source_environment_id:
    description: "Override the source environment that we are cloning from."
    default: "master"
    required: false
  update_environment_access_role_id:
    description: "The id of the Role that needs to gain access to the ephemeral environment."
    required: false

outputs:
  environment_url:
    description: "Contentful environment URL"
  environment_name:
    description: "Contentful environment name"
  cda_token:
    description: "Content Delivery API token created for given ephemeral environment"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "red"
