name: Merge

on:
  push:
    branches:
    - main
    paths-ignore:
    - .dockerignore
    - '.github/**'
    - .gitignore
    - '.husky/**'
    - '**/*.md'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  codeql:
    uses: ./.github/workflows/call-javascript-codeql.yml

  lint:
    uses: ./.github/workflows/call-javascript-lint.yml
